### ISSUE TITLE
Crashed non-stop

### ISSUE THREAD

**Issue by LegendLength** [jadedcat/MF3Configs#35] opened 2016-05-30 08:33 UTC
Crashed when creating a new world.  Tried again with the same world and it managed to load.  Then crashed a few seconds later when i went to NEI and did a mouseover over a few items.

Managed to load it back up and explore for a minute or two before another crash.

**Comment by ghost** [comment] 2016-09-18 05:31
Duplicate of #32

**Closed as completed by ghost** 2016-09-18 05:31 UTC
