### ISSUE TITLE
Version SSP Mod Update crash when opening world

### ISSUE THREAD

**Issue by Kerellian** [jadedcat/MF3Configs#31] opened 2016-04-25 00:42 UTC
When i try to go back into a world after I either save and exit or it crashes i get the following errors
http://pastebin.com/7cUkY7up

this has happened on the updated client and a fresh install after deleting all files

**Comment by Stargazer0613** [comment] 2016-04-25 14:12
We are also having similar issues, where updating the pack has causing errors with the NEI. When trying to click to check for recipes the whole game will crash. My husband and I enjoy your mods very much. We hope the issue is resolved soon. 

Although in inspite of the new update errors, we  temporarily fixed the issue by downloading the previous version of MagicFarm 3.

**Comment by Kerellian** [comment] 2016-04-25 15:57
i am having the same issue with NEI

**Comment by ryutoshirazen** [comment] 2016-05-03 04:13
I had the same problem but fixed it. I'm using the curse client.
Steps:
_If you are using curse client you will need to unlock the profile._
1. Update CodeChickenCore to version 1.7.10-1.0.7.47-universal.jar
2. Update NotEnoughitems to version 1.7.10-1.0.5.118-universal.jar
3. Update NEI integration to version MC1.7.10-1.1.2.jar
4. Update NEI Addons to version 1.12.14.40-mc1.7.10.jar

**Comment by ghost** [comment] 2016-05-13 20:15
Duplicate of #32

**Closed as completed by ghost** 2016-05-13 20:15 UTC
