### ISSUE TITLE
Forestry / NEIIntegration causing client crash

### ISSUE THREAD

**Issue by LemADEC** [jadedcat/MF3Configs#33] opened 2016-05-23 04:41 UTC
We are frequently experiencing the following client crash:

```
[21:27:50] [Client thread/INFO]: Client received server config settings.
[21:27:50] [Client thread/INFO]: CHEAT_SHEET[true], WARDED_STONE[true], MIRRORS[true], HARD_NODES[false], WUSS_MODE[false], RESEARCH_DIFFICULTY[-1], ASPECT_TOTAL_CAP[8000
[21:27:50] [Client thread/INFO]: Receiving Server Configuration...
[21:27:50] [Client thread/ERROR]: Failed to find identifier for: net.minecraft.item.ItemBlock@6a3a5537
[21:27:50] [Client thread/ERROR]: Failed to find identifier for: mods.natura.items.BerryMedley@37199858
[21:27:50] [Client thread/ERROR]: Failed to find identifier for: com.kentington.thaumichorizons.common.items.ItemGolemBellTH@dd7fc3e
[21:27:54] [Client thread/INFO]: Loading: Forestry NEI Integration
[21:27:54] [Client thread/INFO]: Script handler ready. Waiting for a while to ensure all other mods are done messing with NEI.
[21:27:55] [Client thread/INFO]: Added NEI integration
[21:27:55] [Client thread/ERROR]: Failed to load Flower root, Botany support disabled
[21:27:55] [Client thread/INFO]: Loaded Extra Bees comb item: binnie.extrabees.products.ItemHoneyComb@7b4c110c (binnie.extrabees.products.ItemHoneyComb@7b4c110c)
[21:27:55] [Client thread/INFO]: Loaded TB comb item: magicbees.item.ItemComb@61001ed7
[21:27:55] [Client thread/INFO]: Loaded Magic Bees comb item: magicbees.item.ItemComb@61001ed7 (magicbees.item.ItemComb@61001ed7)
[21:27:55] [Client thread/INFO]: Loading integration: Minecraft / Forge
[21:27:55] [Client thread/INFO]: Loading integration: Forestry
[21:27:55] [Client thread/ERROR]: There was a critical exception handling a packet on channel NEI
java.lang.NoClassDefFoundError: forestry/factory/gadgets/MachineBottler$RecipeManager
    at tonius.neiintegration.mods.forestry.RecipeHandlerBottler.prepare(RecipeHandlerBottler.java:29) ~[RecipeHandlerBottler.class:?]
    at tonius.neiintegration.IntegrationBase.registerHandler(IntegrationBase.java:18) ~[IntegrationBase.class:?]
    at tonius.neiintegration.mods.forestry.ForestryIntegration.loadConfig(ForestryIntegration.java:21) ~[ForestryIntegration.class:?]
    at tonius.neiintegration.NEIIntegrationConfig.loadConfig(NEIIntegrationConfig.java:12) ~[NEIIntegrationConfig.class:?]
    at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:278) ~[NEIClientConfig.class:?]
    at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:208) ~[NEIClientConfig.class:?]
    at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) ~[NEICPH.class:?]
    at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) ~[NEICPH.class:?]
    at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:100) ~[PacketCustom$ClientInboundHandler.class:?]
    at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:77) ~[PacketCustom$CustomInboundHandler.class:?]
    at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:64) ~[PacketCustom$CustomInboundHandler.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: forestry.factory.gadgets.MachineBottler$RecipeManager
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
    ... 37 more
Caused by: java.lang.NullPointerException
[21:27:55] [Netty Client IO #1/INFO]: Restoring client configs.
[21:27:55] [Netty Client IO #1/INFO]: Loading configuration files
```

It seems more frequent when connecting for the first time.

The pack currently uses NEI Integration 1.0.12 and Forestry 4.2.11.59 which are incompatible. I guess we need to update NEI Integration or disable its Forestry support.

**Comment by ghost** [comment] 2016-09-18 05:32
Duplicate of #32

**Closed as completed by ghost** 2016-09-18 05:32 UTC
